### PR TITLE
Unnamed Levels Fix

### LINKED ISSUE #217: ETABS_Toolkit: Levels pushed with no name cause ETABS to crash
#### Description:
Levels without names successfully are pushed to ETABS, but ETABS crashes when you try to show the levels.

#### How to replicate:

1. Push levels with no name
2. Switch to ETABS
3. Edit menu > Edit Stories and Grids
4. Crash!

#### Expected behaviour:
ETABS Adapter should fail to push levels without names, or provide default names.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/s/BHoM/ESv1hcEfsepAh3GlrMjjW58BJGayp-W1CNtCj-1_cyjOGQ?e=7EBfgD

### PR DESCRIPTION
**Pull request by kThorsager**
### Issues addressed by this PR
 Closes #217 
Levels without names are given one based on which index it has among the other levels. 

Shouldn't cause any issues as you can only push levels once and they are already ordered by height

 ### Test files
https://burohappold.sharepoint.com/:u:/s/BHoM/EZsO9ZaRESROnH27441iHpYBSJltmCfsTt4jAAyYKzKcrg?e=2nyYGG

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: Etabs_Adapter/Create/Level.cs [hunk 1]
```diff
@@ -48,7 +48,10 @@ private bool CreateCollection(IEnumerable<Level> levels)
 
             List<Level> levelList = levels.OrderBy(x => x.Elevation).ToList();
 
-            string[] names = levelList.Select(x => x.Name).ToArray();
+            if (levelList.Any(x => x.Name.Length == 0))
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/Create/Level.cs]: would change `x => x.Name.Length == 0` to `x => string.IsNullOrWhiteSpace(x)`

File: Etabs_Adapter/Create/Level.cs [hunk 2]
```diff
@@ -48,7 +48,10 @@ private bool CreateCollection(IEnumerable<Level> levels)
...
+                Engine.Reflection.Compute.RecordWarning("Unnamed levels have been given name according to their height index: Level 'i'");
+
+            string[] names = levelList.Select((x,i) => x.Name.Length == 0 ? "Level " + i.ToString() : x.Name).ToArray();
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/Create/Level.cs]: same as above
