### PR TITLE
Fix Bug when Pushing Bars to ETABS21

### LINKED ISSUE #482: Fix Bug when Creating Bars in ETABS21
#### Description:
When running the push of bars using ETABS 21, the  ETABS API method cFrameObj.SetInsertionPoint() called within the BHoM Create.Bar.cs class fires an exception that interrupts the push.
Neither the BHoM Code and the ETABS API method have changed since the previous version (ETABS 20).
This bug prevents any push of bar objects to ETABS 21 models using the BHoM.

Bug GH Canvas Screenshot

Bug VS Code Screenshot

#### Steps to reproduce:
1. Activate the adapter connecting to an instance of ETABS 21
2. Push bar objects into an ETABS 21 Model

#### Expected behaviour:
Bars get pushed into the ETABS 21 model as expected.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/%23482-FixBugWhenCreatingBarsInEtabs21/BHoM%207.3.1%20Test%20-%20Bar%20Object%20Push%20to%20ETABS%2021%201.gh?csf=1&web=1&e=2XWgCj

### PR DESCRIPTION
**Pull request by GCRA101**
### Issues addressed by this PR

 Closes #482 

Bug VS Code Screenshot2

image

ETABS Toolkit now able to push bars to ETABS 21 by skipping not-working API function by checking running ETABS version.

 ### Test files
Grasshopper File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23487-FixBugPushBarsToETABS21/BHoM%207.3.1%20Test%20-%20Bar%20Object%20Push%20to%20ETABS%2021%201.gh?csf=1&web=1&e=FQ2bKd

ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23487-FixBugPushBarsToETABS21/Test%20ETABS%20Model.EDB?csf=1&web=1&e=JE5bz2

 ### Changelog

- Added extraction of ETABS Version number as a string in Adapter constructor
- Use of ETABS Version Number in the create() method for bars to prevent api bug from popping up

### CODE REVIEW

File: Etabs_Adapter/ETABSAdapter.cs [hunk 1]
```diff
@@ -60,6 +60,7 @@ public partial class ETABSAdapter : BHoMAdapter
         public const string ID = "ETABS_id";
 
         public string FilePath { get; set; }
+        public string etabsVersion;
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/ETABSAdapter.cs:63]: Please change this to one of the following:

Option 1:
```suggestion
        private string m_EtabsVersion;
```

and move it down to the private fields (the m_app, m_model etc)

Option 2:
If you want it available in the UI, then make it a property (getter and setter) and capital letter
```suggestion
        public string EtabsVersion { get; set; }
```

File: Etabs_Adapter/CRUD/Create/Bar.cs [hunk 2]
```diff
@@ -153,10 +153,15 @@ private bool SetObject(Bar bhBar)
                 offset2[2] = offset.End.Y;
             }
 
-            if (m_model.FrameObj.SetInsertionPoint(name, (int)bhBar.InsertionPoint(), false, bhBar.ModifyStiffnessInsertionPoint(), ref offset1, ref offset2) != 0)
-            {
-                CreatePropertyWarning("Insertion point and perpendicular offset", "Bar", name);
-                ret++;
+
+            // Avoid following operation if ETABS Version is ETABS21...
+            if (!this.etabsVersion.Contains("21")) {
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Create/Bar.cs:158]: Would try to make this a bit more safe, to avoid a null case, as well as the off chance that the build or the patch could be 21. Would suggest something like the following:

```suggestion
            // Avoid following operation if ETABS Version is ETABS21...
            string majorVersion = "";
            if(this.etabsVersion != null && this.etabsVersion.Contains("."))
                majorVersion = this.etabsVersion.Split('.')[0];

            if (majorVersion != "21") 
            {
```

As an alternative to the above, you could do the work of finding the major version when you get it out in the first place in the adapter constructor. I will leave it to you to decide what you like best.

File: Etabs_Adapter/CRUD/Create/Bar.cs [hunk 3]
```diff
@@ -153,10 +153,15 @@ private bool SetObject(Bar bhBar)
...
+                if (m_model.FrameObj.SetInsertionPoint(name, (int)bhBar.InsertionPoint(), false, 
+                    bhBar.ModifyStiffnessInsertionPoint(), ref offset1, ref offset2) != 0)
+                {
+                    CreatePropertyWarning("Insertion point and perpendicular offset", "Bar", name);
+                    ret++;
+                }
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Create/Bar.cs:164]: Would add an else statement here (for the case that ETABS is on version 21), and check if the insertion point fragment has been set to the bar. Something like:

`else if(bhBar.FindFragment<InsertionPoint>() != null);`

and raise a warning if this is the case, letting the user know that insertion point pushing is unsupported for ETABS 21.

**Review by IsakNaslundBh — DISMISSED** [review]
General principle of this looks great now. Just have some nitty gritty comments on formalia, then from a code standpoint I am happy with this. I do not have ETABS 21 installed on my machine, so will need to rely on someone else to test as well before merging, but before that, please see comments below.

File: Etabs_Adapter/CRUD/Create/Bar.cs (hunk 3 above)
Comment (GCRA101) [reply Etabs_Adapter/CRUD/Create/Bar.cs:168]: @IsakNaslundBh, thanks for the comment.
Incorporated in the code and now available in latest commit.

**Comment by GCRA101** [comment]
@IsakNaslundBh,

thanks for the review and for the comments.
All incorporated in the code now and tested back using the test gh script also used previously.
All working fine ;)

link to latest commit: https://github.com/BHoM/ETABS_Toolkit/pull/487/commits/e30ce4356293ccf522dd0e7986f6bb485a58422a

**Comment by IsakNaslundBh** [comment]
@Chrisshort92 I am happy with this from a pure code perspective now. It still needs a functional review (test) by someone. Would you be able to assist with that, or find someone who can? :)

**Review by albertbg028 — APPROVED** [review]
Works!

PR Review 487

**Comment by GCRA101** [comment]
@BHoMBot check project-compliance

**Comment by GCRA101** [comment]
@BHoMBot check ready-to-merge

**Comment by GCRA101** [comment]
fyi
@Chrisshort92 , @peterjamesnugent , PR ready to merge ;)
