### PR TITLE
Fix Issue with Pushing Levels by using PriorityTypes

### LINKED ISSUE #435: Levels are not pushing to a new model and an error is incorrectly raised
#### Description:

When pushing several object `type`s such as `Levels`, `Floors` and `Walls` - the `Levels` do not push and return an error for not pushing to a new model (despite the model being new).

When pushed independently the `Levels` push fine.

#### Steps to reproduce:

See test script.

#### Expected behaviour:

Levels to push without error.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/%23435-LevelsNotPushingWithOtherObjects?csf=1&web=1&e=vzabMA

### PR DESCRIPTION
**Pull request by GCRA101**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Adapter/pull/393

 ### Issues addressed by this PR

Closes #435 

ETABS vs GH View Levels Push_Commented

ETABS Toolkit now able to push objects and levels together by using priorities on top of dependencies for sorting the objects to push.

 ### Test files
Video Demonstration - Issue
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Push%20Levels%20Issue.mp4?csf=1&web=1&e=7cEacd
Video Demonstration - Solution
https://burohappold.sharepoint.com/:v:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Push%20Levels%20Sorted.mp4?csf=1&web=1&e=cDUbje
Json File
https://burohappold.sharepoint.com/sites/BHoM/_layouts/15/download.aspx?UniqueId=aa695dbddee44123b35aecc6843d658a&e=mvnMou
Grasshopper File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Test%20Script.gh?csf=1&web=1&e=Lzfzec
Etabs File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23480-AddPriorityTypesForPush/Test%20ETABS%20Model.EDB?csf=1&web=1&e=lj7JY7

 ### Changelog
- Added class "PriorityTypes"
- Added implementation of HandlePriorities attribute for the ETABS Adapter

### CODE REVIEW

File: Etabs_Adapter/Types/PriorityTypes.cs [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                {typeof(Bar),4 },
+                {typeof(ISurfaceProperty),5 },
+                {typeof(Panel),6 },
+                {typeof(RigidLink),7 },
+                {typeof(LinkConstraint),8 },
+                {typeof(Loadcase),9 },
+                {typeof(IElementLoad<Node>),10 },
+                {typeof(IElementLoad<Bar>),11 }
+            };
+
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/Types/PriorityTypes.cs:67]: With suggested changes to the BHoM_Adapter, this can simply be this. Think this should not be instead of the dependency types, but just for exceptional cases where that is not enough. 

```suggestion
            PriorityTypes = new List<Type>
            {
                {typeof(Level)},
            };
```

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
TO align with suggested changes in the BHoM_Adapter

File: Etabs_Adapter/Types/PriorityTypes.cs (hunk 1 above)
Comment (GCRA101) [reply Etabs_Adapter/Types/PriorityTypes.cs]: @IsakNaslundBh , thanks for the suggestion.
Incorporated and commited.

**Comment by IsakNaslundBh** [comment]
Happy with this from a code perspective now, and have dismissed my review. @Chrisshort92 Could you please assist in testing this from a functionality point of view?

File: Etabs_Adapter/ETABSAdapter.cs [hunk 2]
```diff
@@ -84,7 +84,9 @@ public ETABSAdapter(string filePath = "", EtabsSettings etabsSetting = null, boo
             AdapterIdFragmentType = typeof(ETABSId);
             BH.Adapter.Modules.Structure.ModuleLoader.LoadModules(this);
             SetupDependencies();
+            SetupPriorities();
             SetupComparers();
+            m_AdapterSettings.HandlePriorities = true;
```
Comment (HugoVanLooveren) [inline Etabs_Adapter/ETABSAdapter.cs:89]: Error when building (after having build [#393](https://github.com/BHoM/BHoM_Adapter/pull/393)):
Could not find out myself why, @GCRA101 
image

Comment (GCRA101) [reply Etabs_Adapter/ETABSAdapter.cs:89]: @HugoVanLooveren , all sorted now. Code updated in both BHoM_Adapter and ETABS_Toolkit accordingly. ;)

**Comment by peterjamesnugent** [comment]
@HugoVanLooveren to complete a functionality review.

**Review by HugoVanLooveren — COMMENTED** [review]
Tested with ETABS 21 & 19
Used BHoM Version 7.2.1.0

With 19 it all worked (opened clean ETABS file, as the example file was for 20)

With 21, the levels got pushed, however, only 1 bar got pushed. 
Got this error:
1. This component failed to run properly.
- Error: Unable to cast object of type 'System.Boolean' to type 'System.Double[]'.
- Occured in  BH.UI.Base.Caller.Run(List`1 inputs)
     called from BH.UI.Base.Caller.Run()
- Are you sure you have the correct type of inputs? Check their description for more details.

**Comment by HugoVanLooveren** [comment]
@GCRA101 & @peterjamesnugent 
Just had a look and ETASB 21 did not work. 
Dunno if that should become a new issue or something though, as the levels got pushed properly.

**Comment by GCRA101** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
> @GCRA101 & @peterjamesnugent Just had a look and ETASB 21 did not work. Dunno if that should become a new issue or something though, as the levels got pushed properly.

ETABS21 is being covered in a seperate PR:

**Review by peterjamesnugent — APPROVED** [review]
Approving based on @HugoVanLooveren's review, and the issue with Etabs21 being covered in a seperate PR:
https://github.com/BHoM/ETABS_Toolkit/pull/483

**Comment by GCRA101** [comment]
@BHoMBot check ready-to-merge
