### PR TITLE
Fix all load types returned when trying to pull not yet implemented load type

### LINKED ISSUE #323: ETABS_Toolkit: All load types returned when trying to pull not yet implemented load type
#### Description:

When trying to pull a type not yet implemented, such as `PointAcceleration` you instead get a list of most other loads back.

#### Expected behaviour:

A warning should be raised. All loads should only be returned when trying to pull with the `ILoad` interface.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/Em_LdUZqgX1KuIVqdNMiGJcBlPpuLhdHOREUu3lv_eSfTQ?e=t6wvmC

### PR DESCRIPTION
**Pull request by kThorsager**
### Issues addressed by this PR

 Closes #323 
As title
 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: Etabs_Adapter/CRUD/Read/Load.cs [hunk 1]
```diff
@@ -56,36 +56,70 @@ public partial class ETABS2016Adapter : BHoMAdapter
...
+                typeCouldBeRead = true;
             }
+
+            if (!typeCouldBeRead)
+            {
+                Engine.Reflection.Compute.RecordError("The load type " + type.GetType().Name + "is not implemented for ETABS and could not be read.");
+            }
+            else if (loads.Count == 0)
+            {
+                Engine.Reflection.Compute.RecordWarning("No loads found in ETABS of that type.");
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Read/Load.cs:118]:
```suggestion
                Engine.Reflection.Compute.RecordWarning("No loads found in ETABS of the requested type.");
```

File: Etabs_Adapter/CRUD/Read/Load.cs [hunk 2]
```diff
@@ -56,36 +56,70 @@ public partial class ETABS2016Adapter : BHoMAdapter
...
+
+            if (type.IsAssignableFrom(typeof(BarPointLoad)))
+            {
+                loads.AddRange(ReadBarPointLoad(loadcaseList));
+                typeCouldBeRead = true;
             }
+
+            if (!typeCouldBeRead)
+            {
+                Engine.Reflection.Compute.RecordError("The load type " + type.GetType().Name + "is not implemented for ETABS and could not be read.");
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Read/Load.cs:114]:
```suggestion
                Engine.Reflection.Compute.RecordError("The load type " + type.GetType().Name + " is not implemented for ETABS and could not be read.");
```

File: Etabs_Adapter/CRUD/Create/Load.cs [hunk 3]
```diff
@@ -324,10 +324,18 @@ public void SetLoad(GravityLoad gravityLoad, bool replace)
...
         }
 
+
         /***************************************************/
         /****       Helper Methods                      ****/
         /***************************************************/
 
+        private void SetLoad(ILoad load, bool replace)
+        {
+            Engine.Reflection.Compute.RecordError("Load of type " + load.GetType().Name + " not supported.");
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Create/Load.cs:334]:
```suggestion
            Engine.Reflection.Compute.RecordError("Load of type " + load.GetType().Name + " is not supported.");
```

File: Etabs_Adapter/CRUD/Read/Load.cs [hunk 4]
```diff
@@ -56,36 +56,70 @@ public partial class ETABS2016Adapter : BHoMAdapter
...
+
+            if (type.IsAssignableFrom(typeof(BarPointLoad)))
+            {
+                loads.AddRange(ReadBarPointLoad(loadcaseList));
+                typeCouldBeRead = true;
+            }
+
+            if (!typeCouldBeRead)
+            {
+                Engine.Reflection.Compute.RecordError("The load type " + type.GetType().Name + " is not implemented for ETABS and could not be read.");
```
Comment (IsakNaslundBh) [inline Etabs_Adapter/CRUD/Read/Load.cs:114]:
```suggestion
                Engine.Reflection.Compute.RecordError("The load type " + type.Name + " is not implemented for ETABS and could not be read.");
```
